version: '3'
<<<<<<< HEAD
services:
  web:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
=======
services: 
  web:
    stdin_open: true
>>>>>>> 6cac22fac82657d1ed53749a420c03c62cf9928f
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
<<<<<<< HEAD
      - '3000:3000'
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ['npm', 'run', 'test']
=======
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
>>>>>>> 6cac22fac82657d1ed53749a420c03c62cf9928f
